project:
  title: "Single Cell Gene Expression"
  author: "Zifo RnD Solutions"
  output-dir: docs
  execute-dir: project
  render:
    - analysis/data-loading.qmd
    - analysis/droplet-processing.qmd
    - analysis/quality-control.qmd
    - analysis/normalization.qmd
    - analysis/feature-selection.qmd
