---
title: "Dimensionality reduction"
params:
    perplexity: 30
    max_iter: 500
    n_neighbors: 15
    n_epochs: 500
    min_dist: 0.01
---

```{r, child = "big-data.Rmd"}
```

Load Bioconductor package(s):

```{r}
library(scuttle)
```

Load CRAN package(s):

```{r}
library(ggforce)
```

Read experiment object(s):

```{r}
sce <- readRDS("05-feature-selection.rds")
```

## Principal components analysis

Extract highly variable genes:

```{r}
hvg <- lapply(sce, rowSubset, "HVG")
```

## t-SNE

Perform t-SNE for the cells:

```{r}
sce <- runTSNE(
    x = sce,
    perplexity = params$perplexity,
    max_iter = params$max_iter, 
    external_neighbors = TRUE, 
    BNPARAM = BNP, 
    BPPARAM = BPP,
    dimred = "corrected"
)
```

```{r}
ggcells(sce, aes(TSNE.1, TSNE.2)) + 
    geom_point() + 
    theme_no_axes() + 
    theme(aspect.ratio = 1)
```

## UMAP 

Perform UMAP for the cells:

```{r}
sce <- runUMAP(
    x = sce, 
    n_neighbors = params$n_neighbors, 
    n_epochs = params$n_epochs, 
    min_dist = params$min_dist, 
    external_neighbors = TRUE, 
    BNPARAM = BNP, 
    BPPARAM = BPP, 
    dimred = "PCA"
)
```

```{r}
ggcells(sce, aes(UMAP.1, UMAP.2)) + 
    geom_point() + 
    theme_no_axes() + 
    theme(aspect.ratio = 1)
```

## Output

Save experiment object(s):

```{r}
saveRDS(sce, file = "reduced-dimensions.rds")
```

Print session information:

```{r}
sessionInfo()
```
